package commands

import (
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// AppRow is one installed app for list/status/export output. Column order
// matches the ScoopApps ps1xml view: Name/Version/Source/Updated/Info.
type AppRow struct {
	Name    string
	Version string
	Source  string
	Updated string
	Info    string
	Global  bool
	Hold    bool
}

// CollectApps mirrors the scoop-list.ps1 enumeration over user and global
// scopes with an optional regex query filter.
func (e *Env) CollectApps(query string) ([]AppRow, error) {
	var re *regexp.Regexp
	if query != "" {
		var err error
		re, err = regexp.Compile("(?i)" + query)
		if err != nil {
			return nil, err
		}
	}
	var rows []AppRow
	for _, global := range []bool{false, true} {
		for _, app := range e.InstalledApps(global) {
			if re != nil && !re.MatchString(app) {
				continue
			}
			rows = append(rows, e.describeApp(app, global))
		}
	}
	return rows, nil
}

func (e *Env) describeApp(app string, global bool) AppRow {
	row := AppRow{Name: app, Global: global}
	ver := e.CurrentVersion(app, global)
	row.Version = ver
	info, infoPath := e.InstallInfoFor(app, ver, global)
	if info == nil {
		if dir, err := os.Stat(e.AppDir(app, global)); err == nil {
			row.Updated = formatTime(dir.ModTime())
		}
		row.Info = "Install failed"
		return row
	}
	row.Hold = info.Hold
	switch {
	case info.Bucket != "":
		row.Source = info.Bucket
	case info.URL == filepath.Join(e.UserManifestsDir(), app+".json"):
		row.Source = "<auto-generated>"
	case info.URL != "":
		row.Source = info.URL
	}
	if fi, err := os.Stat(infoPath); err == nil {
		row.Updated = formatTime(fi.ModTime())
	}
	var parts []string
	if e.isDeprecated(app, info.Bucket) {
		parts = append(parts, "Deprecated package")
	}
	if global {
		parts = append(parts, "Global install")
	}
	if info.Hold {
		parts = append(parts, "Held package")
	}
	if info.Architecture != "" && info.Architecture != e.Arch {
		parts = append(parts, info.Architecture)
	}
	row.Info = strings.Join(parts, ", ")
	return row
}

func (e *Env) isDeprecated(app, bucket string) bool {
	deprecated := filepath.Join(e.bucketRoot(bucket), "deprecated")
	matches, _ := filepath.Glob(filepath.Join(deprecated, sanitaryPath(app)+".json"))
	if len(matches) > 0 {
		return true
	}
	// Buckets with a bucket/ subdir may nest deprecated manifests deeper.
	found := false
	_ = filepath.WalkDir(deprecated, func(p string, d os.DirEntry, err error) error {
		if err == nil && !d.IsDir() && strings.EqualFold(d.Name(), sanitaryPath(app)+".json") {
			found = true
		}
		return nil
	})
	return found
}

// totalInstalled counts installed apps across both scopes before query
// filtering, mirroring the scoop-list.ps1:19 empty check.
func totalInstalled(env *Env) int {
	return len(env.InstalledApps(false)) + len(env.InstalledApps(true))
}

// RunList mirrors libexec/scoop-list.ps1. The query is a regex matched
// against app names. The "Installed apps[:]"/"Installed apps matching"
// preamble matches scoop-list.ps1:24 verbatim and is not invented. An empty
// install warns with exit 1 even when a query is supplied (classic checks
// the app list before filtering); a query with no hits over a non-empty
// install prints the preamble plus the header-only table with exit 0.
func RunList(env *Env, out io.Writer, args []string) int {
	var query string
	if len(args) > 0 {
		query = args[0]
	}
	rows, err := env.CollectApps(query)
	if err != nil {
		Errorf(out, "%s", err.Error())
		return 1
	}
	if len(rows) == 0 && totalInstalled(env) == 0 {
		Warnf(out, "There aren't any apps installed.")
		return 1
	}
	if query != "" {
		Successf(out, "Installed apps matching '%s':", query)
	} else {
		Successf(out, "Installed apps:")
	}
	table := make([][]string, 0, len(rows))
	for _, r := range rows {
		table = append(table, []string{r.Name, r.Version, r.Source, r.Updated, r.Info})
	}
	renderTable(out, []string{"Name", "Version", "Source", "Updated", "Info"}, table)
	return 0
}
