package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

type scoopfileApp struct {
	Name    string `json:"Name"`
	Source  string `json:"Source"`
	Version string `json:"Version"`
	Info    string `json:"Info"`
}

type scoopfileBucket struct {
	Name   string `json:"Name"`
	Source string `json:"Source"`
}

// readScoopfile loads a scoopfile from a local path. URL scoopfiles
// need the download layer and report as unsupported in this phase.
func readScoopfile(scoopfile string) (map[string]any, []byte, error) {
	if isURL(scoopfile) {
		return nil, nil, fmt.Errorf("URL scoopfiles need the download backend")
	}
	raw, err := os.ReadFile(scoopfile)
	if err != nil {
		return nil, nil, err
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, nil, err
	}
	return doc, raw, nil
}

func importAppSource(item scoopfileApp, bucketNames []string) string {
	for _, b := range bucketNames {
		if strings.EqualFold(item.Source, b) {
			return b + "/" + item.Name
		}
	}
	if item.Source == "<auto-generated>" {
		return item.Name + "@" + item.Version
	}
	if item.Source != "" {
		return item.Source
	}
	return item.Name
}
